### ISSUE TITLE
关于使用Go语言每分钟处理1百万请求的一个问题的看法

### ISSUE THREAD

**Issue by bigpigeon** [itfanr/articles-about-golang#2]
```
go func(job Job) {
    // try to obtain a worker job channel that is available.
    // this will block until a worker is idle
        jobChannel := <-d.WorkerPool

    // dispatch the job to the worker job channel
    jobChannel <- job
}(job)
```

代码中的这部分会在并发量过大的时候导致大量go router和抢占WorkerPool吧？
我觉得应该把这部分提到外面去，通过增大Queue来达到缓存任务的效果

**Comment by itfanr** [comment]
@bigpigeon  谢谢啊。你是说减少底层锁的并发是吧？

**Comment by bigpigeon** [comment]
应该是的，不过我对go底层理解的不深哈
根据你的译文我写了一个[demo](https://github.com/bigpigeon/WorkerPoolDemo)，不过是通过queue来缓存任务，感觉没有出现什么问题，而且goroutines数量减少了不少

**Comment by itfanr** [comment]
@bigpigeon  你的尝试增加了我继续翻译的动力。哈哈！握手~

**Comment by itfanr** [comment]
@bigpigeon  有空你也可以了解下rust语言。rust语言也不错，实时性比较好。

**Comment by bigpigeon** [comment]
嗯，之前也想去了解，不过rust给我的感觉就是太过复杂，写起来可能要注意很多细节，不过听说编译期的错误很清晰好理解，比C++好不少(*￣∇￣*)

**Comment by itfanr** [comment]
@bigpigeon  c++是入门简单，用起来很难，用户体验差，尤其是大项目的内存问题。

估计rust是学起来很难，但是用起来省心。

**Comment by bigpigeon** [comment]
有空我去把rust的example做一遍
